### ISSUE TITLE
[FEATURE]:  Add cli command `databricks labs ucx migrate-tables --what dbfs_root_delta` to migrate DBFS Root Delta Table

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#901] opened 2024-02-06 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

User requires a way to trigger the UC CLI process.

### Proposed Solution

Create a CLI command to kick off the DBFS Root Delta Tables.

**Comment by nfx** [comment] 2024-04-23 12:45
Duplicate of #670

**Closed by nfx** 2024-04-23 12:45 UTC
Labels: migrate/managed, feat/cli, London-Workshop, feat/workflow
