### ISSUE TITLE
[FEATURE]: add command for migrating DBFS_ROOT_NON_DELTA tables

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1230] opened 2024-04-03 08:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

There exists commands for migrating DBFS_ROOT_DELTA, EXTERNAL_SYNC and VIEW tables, but not for DBFS_ROOT_NON_DELTA.

### Proposed Solution

Add command in `runtime.py`.

**Comment by nfx** [comment] 2024-04-22 13:59
Duplicate of https://github.com/databrickslabs/ucx/issues/332

**Closed by nfx** 2024-04-22 13:59 UTC
Labels: migrate/managed
