### ISSUE TITLE
[FEATURE]: Reset inventory tables when rerunning the assessment workflow

### ISSUE THREAD

**Issue by qziyuan** [databrickslabs/ucx#2352] opened 2024-08-02 19:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When customers have updates in the workspace and need to rerun the assessment workflow, they have to first manually clean up the existing data in inventory database tables.
We should run CrawlerBase.reset() before snapshot() in each assessment workflow task.

### Proposed Solution

Run CrawlerBase.reset() before snapshot() in each assessment workflow task.

**Comment by nfx** [comment] 2024-08-03 13:12
duplicate of https://github.com/databrickslabs/ucx/issues/2074

**Closed by nfx** 2024-08-03 13:12 UTC
Labels: enhancement, needs-triage
