### ISSUE TITLE
[BUG]:  Not able to run databricks labs install ucx

### ISSUE THREAD

**Issue by sagpra** [databrickslabs/ucx#2220] opened 2024-07-22 06:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 from databricks.labs.lsql.dashboards import DashboardMetadata, Dashboards
  File "/Users/sagarprajapati/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/labs/lsql/dashboards.py", line 305, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by asnare** [comment] 2024-07-22 08:06
@sagpra: There's a bit of detail missing from this report, such as the complete error message and the steps leading up to it.

What version of the Databricks CLI are you using? I'd like to see:

 * `databricks --version`
 * `databricks labs installed`

**Comment by nfx** [comment] 2024-07-23 14:28
duplicate of #2223

**Closed by nfx** 2024-07-23 14:28 UTC
Labels: bug, feat/installer
