### ISSUE TITLE
Assessment job failures

### ISSUE THREAD

**Issue by johnlourdu** [databrickslabs/ucx#508] opened 2023-10-26 14:03 UTC
I followed the steps from the document but assessment workflow task failed due to below exceptions.

assess_jobs run

File /databricks/spark/python/pyspark/sql/types.py:2008, in _make_type_verifier.<locals>.verify_nullability(obj)
   2006         return True
   2007     else:
-> 2008         raise PySparkValueError(
   2009             error_class="CANNOT_BE_NONE",
   2010             message_parameters={"arg_name": "obj"},
   2011         )
   2012 else:
   2013     return False

PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.

assess_pipelines

File /databricks/spark/python/pyspark/errors/exceptions/captured.py:194, in capture_sql_exception.<locals>.deco(*a, **kw)
    190 converted = convert_exception(e.java_exception)
    191 if not isinstance(converted, UnknownException):
    192     # Hide where the exception came from that shows a non-Pythonic
    193     # JVM exception message.
--> 194     raise converted from None
    195 else:
    196     raise

AnalysisException: Delta table `ucx`.`pipelines` doesn't exist.

assess_global_init_scripts

File /databricks/spark/python/pyspark/sql/types.py:2008, in _make_type_verifier.<locals>.verify_nullability(obj)
   2006         return True
   2007     else:
-> 2008         raise PySparkValueError(
   2009             error_class="CANNOT_BE_NONE",
   2010             message_parameters={"arg_name": "obj"},
   2011         )
   2012 else:
   2013     return False

PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.

assess_clusters
AnalysisException: Delta table `ucx`.`clusters` doesn't exist.

assess_azure_service_principals
AnalysisException: Delta table `ucx`.`azure_service_principals` doesn't exist.

**Comment by william-conti** [comment] 2023-10-30 15:40
@johnlourdu Could you please try using the main branch ? (v0.5.1) it should be fixed

**Comment by johnlourdu** [comment] 2023-10-31 12:48
Hi William

I see only v0.5.0 in main branch

**Comment by nfx** [comment] 2023-11-06 08:26
@johnlourdu unreleased versions are installed with an increment to patch part in semver

**Comment by nfx** [comment] 2023-11-07 23:47
Duplicate of #503

**Closed by nfx** 2023-11-07 23:47 UTC
Labels: bug, step:assessment
