### ISSUE TITLE
[BUG]: [UCX] assessment failed at task assess_workflows

### ISSUE THREAD

**Issue by ddsharmainfo** [databrickslabs/ucx#2988] opened 2024-10-16 16:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running the ucx assessment workflow the job failed with below error:

**ERROR:**
Detected 12 failures: AstroidSyntaxError: Parsing Python code failed:
invalid syntax (, line 1), SystemError: AST constructor recursion depth mismatch (before=72, after=140), SystemError: AST constructor recursion depth mismatch (before=87, after=129), 

### Expected Behavior

assessment workflow should complete without any issue.

### Steps To Reproduce

1. Install UCX 0.44
2. Run the assessment

Wait for assessment completion.

### Cloud

GCP

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
Detected 12 failures: AstroidSyntaxError: Parsing Python code failed:
invalid syntax (, line 1), SystemError: AST constructor recursion depth mismatch (before=72, after=140), SystemError: AST constructor recursion depth mismatch (before=87, after=129), SystemError: AST constructor recursion depth mismatch (before=87, after=130), SystemError: AST constructor recursion depth mismatch (before=87, after=131), SystemError: AST constructor recursion depth mismatch (before=87, after=136), SystemError: AST constructor recursion depth mismatch (before=87, after=138), SystemError: AST constructor recursion depth mismatch (before=87, after=152), SystemError: AST constructor recursion depth mismatch (before=87, after=54), SystemError: AST constructor recursion depth mismatch (before=87, after=81)

09:04:19  INFO [d.l.blueprint.parallel][linting_workflows_1] linting workflows 222/222, rps: 0.052/sec
09:04:19  WARN [d.l.blueprint.parallel] Some 'linting workflows' tasks failed: 95% results available (210/222). Took 1:10:56.355210
09:04:19  INFO [d.l.u.source_code.jobs] Saving 7484 linting problems...
09:04:47 ERROR [d.labs.ucx] Execute `databricks workspace export //Applications/ucx/logs/assessment/run-185914262041462-0/assess_workflows.log` locally to troubleshoot with more details. Detected 12 failures: AstroidSyntaxError: Parsing Python code failed:
invalid syntax (<unknown>, line 1), SystemError: AST constructor recursion depth mismatch (before=72, after=140), SystemError: AST constructor recursion depth mismatch (before=87, after=129), SystemError: AST constructor recursion depth mismatch (before=87, after=130), SystemError: AST constructor recursion depth mismatch (before=87, after=131), SystemError: AST constructor recursion depth mismatch (before=87, after=136), SystemError: AST constructor recursion depth mismatch (before=87, after=138), SystemError: AST constructor recursion depth mismatch (before=87, after=152), SystemError: AST constructor recursion depth mismatch (before=87, after=54), SystemError: AST constructor recursion depth mismatch (before=87, after=81)
```

**Comment by nfx** [comment] 2024-10-16 17:59
looks like a duplicate of https://github.com/databrickslabs/ucx/issues/2976

**Closed by nfx** 2024-10-16 17:59 UTC
Labels: bug, needs-triage
