### ISSUE TITLE
[FEATURE]: Download Output of Assessment in a single spreadsheet

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#809] opened 2024-01-17 21:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

After we run UCX successfully and generate the assessment dashboard we use that as an input to conduct effort estimation for UC Upgrade. Usually we have to get the csv output from each visualization widget of the dashboard, save them as separate tabs in a single spreadsheet and share or use for next step, such as coming up with estimated effort for UC upgrade. Can we generate the output already in a spreadsheet format so that it is easier to use that data in the subsequent steps instead of us having to manually generate the spreadsheet of the data already available in inventory tables? 

### Proposed Solution

Generate the output of assessment already in a spreadsheet format so that it is easier to use that data in the subsequent steps instead of us having to manually generate the spreadsheet of the data already available in inventory tables.

**Comment by nfx** [comment] 2024-01-18 09:22
@dipankarkush-db create a CLI command, i'm not sure it's possible to get that in dashboard ui

**Comment by dipankarkush-db** [comment] 2024-01-18 14:23
@nfx - Not in the dashboard UI but inside the `.ucx` folder as a subfolder. Just like we have `queries` subfolder, similarly we can have `assessment_output` sub folder. At least the output from the initial assessment run can be saved in spreadsheet format. It will save quite a lot of manual effort to analyze the output and estimate effort.

**Comment by nfx** [comment] 2024-01-18 22:01
why do we really need this? i'd rather spend time on something else

**Comment by nfx** [comment] 2024-01-23 10:07
@dipankarkush-db Who analyzes and estimates the effort? How can it be automated?

**Comment by nfx** [comment] 2024-01-30 09:51
Duplicate of #749

**Closed** 2024-01-30 09:51 UTC
Labels: enhancement, step:assessment
