### ISSUE TITLE
[FEATURE]: Single UCX Installation per workspace

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#890] opened 2024-02-05 16:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Each user's UCX installation creates a separate folder. Some tasks, requires the involvement of more than one user which will create a potential issue.

### Proposed Solution

Default installation to the <root folder>/applications/ucx allow the user to override the default and install to the user's folder.

**Comment by nfx** [comment] 2024-02-05 17:43
duplicate of https://github.com/databrickslabs/ucx/issues/803

**Closed by nfx** 2024-02-05 17:43 UTC
Labels: enhancement, installer, London-Workshop
