### ISSUE TITLE
Error migrate-groups-cleanup step

### ISSUE THREAD

**Issue by wsilveira-usp** [databrickslabs/ucx#365] opened 2023-10-03 14:27 UTC
In the migrate-groups-cleanup step, the job is supposed to remove workspace-level backup groups as stated in the Repo and README generated by the tool.

However, the [code](https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/runtime.py#L205C22-L205C22) looks for groups without the defined prefix, which throws an error as the original group no longer exists as a workspace-level one.

Error:
![image](https://github.com/databrickslabs/ucx/assets/74460035/c62045bd-b0a8-4954-9daf-e65a9106bc36)

Workaround: manually delete backup groups.

**Comment by nfx** [comment] 2023-10-03 18:19
this is a duplicate of https://github.com/databrickslabs/ucx/issues/327

**Closed by nfx** 2023-10-03 18:19 UTC
Labels: bug
