### ISSUE TITLE
[BUG]: TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by CedricEdouardKassi** [databrickslabs/ucx#2148] opened 2024-07-10 14:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I'm facing with this issue when trying to create databricks account group from local Databricks group with the following command : 
databricks labs ucx create-account-groups --workspace-ids <xxxxxxxx> --debug -p <profile_name> 

I got this error: 

TypeError: cannot pickle '_thread.lock' object

For information, I'm megastore admin and Databricks account admin.

<img width="530" alt="image" src="https://github.com/databrickslabs/ucx/assets/6081876/d66ee6e4-53a0-4202-8f22-9a3e817f1796">

### Steps To Reproduce

databricks labs ucx create-account-groups --workspace-ids <xxxxxxxx> --debug -p <profile_name> 

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
ERROR [d.l.ucx.create-account-groups] Failed to call create-account-groups: Traceback (most recent call last):
  File "/Users/cedric/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/labs/blueprint/cli.py", line 113, in _route
    cmd.fn(**kwargs)
  File "/Users/cedric/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py", line 122, in create_account_groups
    ctx.account_workspaces.create_account_level_groups(prompts, ctx.workspace_ids)
  File "/Users/cedric/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account/workspaces.py", line 82, in create_account_level_groups
    all_valid_workspace_groups = self._get_valid_workspaces_groups(prompts, workspace_ids)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account/workspaces.py", line 190, in _get_valid_workspaces_groups
    self._load_workspace_groups(prompts, workspace, all_workspaces_groups)
  File "/Users/cedric/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account/workspaces.py", line 195, in _load_workspace_groups
    client = self.client_for(workspace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account/workspaces.py", line 30, in client_for
    return self._ac.get_workspace_client(workspace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/__init__.py", line 929, in get_workspace_client
    config = self._config.deep_copy()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/config.py", line 526, in deep_copy
    return copy.deepcopy(self)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 238, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.lock' object
```

**Comment by nfx** [comment] 2024-07-10 15:32
looks like an SDK problem

**Comment by arqgroup-charunathan** [comment] 2024-07-16 00:51
Hi @nfx ,
I'm also facing the same issue while executing the same ucx command. 
![image](https://github.com/user-attachments/assets/87dd901d-cd44-478e-9df7-a7d51d954ebe)

**Comment by nikhilmish-db** [comment] 2024-07-17 16:31
We are also facing this issue, and CX is waiting for a resolution.
16:28:19 ERROR [src/databricks/labs/ucx.create-account-groups] TypeError: cannot pickle '_thread.lock' object

**Comment by cekowalski72** [comment] 2024-07-18 19:33
One of my customers is also facing this issue when running "databricks labs ucx sync-workspace-info --profile accounts"

**Comment by nfx** [comment] 2024-07-23 17:09
depends on a bug in SDK

**Comment by qziyuan** [comment] 2024-07-24 06:29
So any code that calls [`AccountClient.get_workspace_client`](https://github.com/databricks/databricks-sdk-py/blob/6a9c534e39e8bb447725d6cdf3612549849f0bdd/databricks/sdk/__init__.py#L935) with SDK v0.29.0 will have this error.
With that, following commands in UCX v0.28.0 and above will suffer from this issue:
- `create-account-groups` command
- `sync-workspace-info` command
- `join-collection` command
- `ensure-assessment-run` command
- `report-account-compatibility`command
- `assign-metastore` command, if `default_catalog` parameter is set.
- UCX installation will fail if has `UCX_FORCE_INSTALL=account`

### Here is a workaround:
The idea is installing a separate older version UCX bins (v0.23.0) in the local laptop. We only need the UCX bins and older version SDK which does not have the above bug, so no need to finish the workspace installation part (deploy workspace config, inventory database, workflows etc.)

1. UCX and all it's dependencies, including the SDK, will be installed in `$HOME/.databricks/labs/ucx/`. So we need to set new $HOME temporarily, like `export HOME=/Users/ziyuan.qin/ucx_v23`. So the older UCX installed later will be separated from the default existing current version UCX.
2. Install UCX v0.23.0: `databricks labs install ucx@v0.23.0 -p <profile>`. Answer no when asked "[ADVANCED] UCX is already installed on this workspace. Do you want to create a new installation?", because just need older UCX and SDK bin to be installed in the laptop, and we don't need following installation and deployment in workspace.
3. Now you can retry those UCX commands failed with `_thread.lock` error.
4. By setting $HOME env, you can control which version of UCX bins to be used.
5. With old version UCX, you need to `databricks auth login` to all workspaces that your command will be executed against, just `databricks auth login` to account console won't be enough. For example:
    - `sync-workspace-info` store all workspace id and name under the account, so you need to `databricks auth login` to all the workspaces.
    - For `create-account-groups` command, you need to `databricks auth login` to all the workspaces listed in `--workspace-ids`.

**Comment by qziyuan** [comment] 2024-07-24 17:56
[ES-1203418](https://databricks.atlassian.net/browse/ES-1203418) is filed to fix the SDK bug.

**Comment by tanyapohn** [comment] 2024-07-26 11:24
> So any code that calls [`AccountClient.get_workspace_client`](https://github.com/databricks/databricks-sdk-py/blob/6a9c534e39e8bb447725d6cdf3612549849f0bdd/databricks/sdk/__init__.py#L935) with SDK v0.29.0 will have this error. With that, following commands in UCX v0.28.0 and above will suffer from this issue:
> 
> * `create-account-groups` command
> * `sync-workspace-info` command
> * `join-collection` command
> * `ensure-assessment-run` command
> * `report-account-compatibility`command
> * `assign-metastore` command, if `default_catalog` parameter is set.
> * UCX installation will fail if has `UCX_FORCE_INSTALL=account`
> 
> ### Here is a workaround:
> The idea is installing a separate older version UCX bins (v0.23.0) in the local laptop. We only need the UCX bins and older version SDK which does not have the above bug, so no need to finish the workspace installation part (deploy workspace config, inventory database, workflows etc.)
> 
> 1. UCX and all it's dependencies, including the SDK, will be installed in `$HOME/.databricks/labs/ucx/`. So we need to set new $HOME temporarily, like `export HOME=/Users/ziyuan.qin/ucx_v23`. So the older UCX installed later will be separated from the default existing current version UCX.
> 2. Install UCX v0.23.0: `databricks labs install ucx@v0.23.0 -p <profile>`. Answer no when asked "[ADVANCED] UCX is already installed on this workspace. Do you want to create a new installation?", because just need older UCX and SDK bin to be installed in the laptop, and we don't need following installation and deployment in workspace.
> 3. Now you can retry those UCX commands failed with `_thread.lock` error.
> 4. By setting $HOME env, you can control which version of UCX bins to be used.
> 5. With old version UCX, you need to `databricks auth login` to all workspaces that your command will be executed against, just `databricks auth login` to account console won't be enough. For example:
>    
>    * `sync-workspace-info` store all workspace id and name under the account, so you need to `databricks auth login` to all the workspaces.
>    * For `create-account-groups` command, you need to `databricks auth login` to all the workspaces listed in `--workspace-ids`.

I'd followed step no. 1 and 2. After I ran `databricks labs install ucx@v0.23.0 -p <profile>`, it raises the error said:
```
Traceback (most recent call last):
  File "/Users/tanyapohn.p/ucx_v23/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 49, in <module>
    from databricks.labs.ucx.contexts.account_cli import AccountContext
  File "/Users/tanyapohn.p/ucx_v23/.databricks/labs/ucx/lib/src/databricks/labs/ucx/contexts/account_cli.py", line 6, in <module>
    from databricks.labs.ucx.account.aggregate import AccountAggregate
  File "/Users/tanyapohn.p/ucx_v23/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account/aggregate.py", line 14, in <module>
    from databricks.labs.ucx.contexts.workspace_cli import WorkspaceContext
  File "/Users/tanyapohn.p/ucx_v23/.databricks/labs/ucx/lib/src/databricks/labs/ucx/contexts/workspace_cli.py", line 16, in <module>
    from databricks.labs.ucx.contexts.application import CliContext
  File "/Users/tanyapohn.p/ucx_v23/.databricks/labs/ucx/lib/src/databricks/labs/ucx/contexts/application.py", line 37, in <module>
    from databricks.labs.ucx.source_code.jobs import WorkflowLinter
  File "/Users/tanyapohn.p/ucx_v23/.databricks/labs/ucx/lib/src/databricks/labs/ucx/source_code/jobs.py", line 14, in <module>
    from databricks.labs.ucx.mixins.wspath import WorkspacePath
  File "/Users/tanyapohn.p/ucx_v23/.databricks/labs/ucx/lib/src/databricks/labs/ucx/mixins/wspath.py", line 9, in <module>
    from pathlib import Path, _PosixFlavour  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '_PosixFlavour' from 'pathlib' (/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py)
Error: installer: exit status 1
```
 I am not quite sure what I missed

**Comment by tanyapohn** [comment] 2024-07-27 13:14
For anyone who faces the same issue as I do when trying to work around, I figured it out the error above produces when installing `v0.23.0`. This can be fixed by installing `v0.23.1` instead since `_PosixFlavour` had been resolved in `v0.23.1` [releases](https://github.com/databrickslabs/ucx/releases/tag/v0.23.1)

**Comment by ouranos** [comment] 2024-08-05 14:16
I'm having the same error on `ucx@0.32.0` when running the `sync-workspace-info` command:

```
ERROR [d.l.ucx.sync-workspace-info] TypeError: cannot pickle '_thread.lock' object
```

Any update on this?

**Comment by qziyuan** [comment] 2024-08-05 17:23
The upstream bug fix is being tracked in this ES ticket https://databricks.atlassian.net/browse/ES-1203418

@ouranos meanwhile you can try the workaround above to run `sync-workspace-info`, or instead use `manual-workspace-info`

**Comment by ouranos** [comment] 2024-08-06 10:44
> The upstream bug fix is being tracked in this ES ticket [databricks.atlassian.net/browse/ES-1203418](https://databricks.atlassian.net/browse/ES-1203418)

This seems to be private so I cannot track the progress.

> @ouranos meanwhile you can try the workaround above to run `sync-workspace-info`, or instead use `manual-workspace-info`

I've used `manual-workspace-info` for now.

**Comment by sagpra** [comment] 2024-08-13 05:40
No proper ucx build is available till now. For every version there is some issues. Others are also getting same issues?

**Comment by qziyuan** [comment] 2024-08-14 18:11
To whom do not have access to https://databricks.atlassian.net/browse/ES-1203418, here is the update:
A PR is created to fix the `cannot pickle '_thread.lock'`. However it will cause a regression that each workspace your command needs to access has to be authenticated in your machine first. The original goal is you authenticate to account once, and then be able to connect to all the workspace you have access to. We still need a better fix. Stay tuned.

**Comment by qziyuan** [comment] 2024-08-16 07:01
> No proper ucx build is available till now. For every version there is some issues. Others are also getting same issues?

@sagpra My customer tried today and the workaround is still working for them. I'm not sure what is the issue in your case. 
If you are blocked by this, one possible temp workaround would be applying the [unreleased fix](databricks/sdk/credentials_provider.py) in https://databricks.atlassian.net/browse/ES-1203418 directly to the SDK code in your laptop: `$HOME/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/credentials_provider.py`

**Comment by sagpra** [comment] 2024-08-16 15:43
OK Thanks, I will check it again

**Comment by JCZuurmond** [comment] 2024-08-28 13:53
- Should be resolved in latest sdk release: https://github.com/databricks/databricks-sdk-py/releases/tag/v0.31.1
- Dependabot will bump the dependency version in ucx shortly

**Comment by JCZuurmond** [comment] 2024-08-30 15:35
Should be resolved when upgrading to the latest version `databricks labs upgrade ucx`. Make sure that you have the latest version of the Databricks cli before upgrading ucx. Please report back if the issue is not resolved.

**Closed by JCZuurmond** 2024-08-30 15:35 UTC
Labels: bug, platform-issue
