### ISSUE TITLE
Group and ACL migration with same group names in multiple Workspaces or environments

### ISSUE THREAD

**Issue by karthickbaskaran-db** [databrickslabs/ucx#579] opened 2023-11-16 01:44 UTC
I have a customer who has 4 Workspaces (dev, test, uat and prod) and their Group names (Workspace groups) are same across all the 4 Workspaces. These groups will have different ACLs in different environment / Workspace. With this setup, we cannot use the UCX script to migrate the Workspace groups to account level, since the ACLs will be overridden. So I would like to have a feature to rename groups before migrating them to account level. Also i noticed that the ucx script is not backing up the Workspace groups. We ran the ucx script, all the jobs were created successfully, we ran the assessment job, we are able to see the dashboard, ucx DB and tables. But when we ran the job 2 (002-apply-permissions-to-backup-group), only the first group is getting backed up and the remaining groups are ignored. Also the README page nor the interactive tutorial reflect the latest changes.

**Comment by FastLee** [comment] 2023-11-16 15:00
What would be an acceptable solution? Apply an environment prefix/suffix to the group name?

**Comment by pohlposition** [comment] 2023-11-20 01:31
Should "the workflow not backing up groups" be considered a bug?

**Comment by karthickbaskaran-db** [comment] 2023-11-21 04:07
@FastLee  - Yes a prefix or suffix to the group name would help.
@pohlposition  - Yes that should be a bug.

**Comment by rlsalcido24** [comment] 2023-11-22 19:25
hey @pohlposition @FastLee @karthickbaskaran-db in a similar vein to this question, what is the expected behavior in situations where customer has 4 Workspaces (dev, test, uat and prod) and their Group names (Workspace groups) are same across all the 4 Workspaces (lets call the group Data Eng)-- the ACLs are also the same but the members are different. When I run the logic in all four workspaces will the account group Data Eng end up with:

a) The same members as it was initially created with (in this case 0 members)
b) The superset of all data eng members across all four workspaces
c) The same members as the most recent workspace the logic was run on
d) Something different

Also would be great if we could more clearly articulate these nuances somewhere-- i know the reprise articulates that an account group with the same name as the workspace group must be created before the migrate group logic is run, but iirc this isnt stated in the readme which is what most customers reference as their source of truth.

**Comment by karthickbaskaran-db** [comment] 2023-11-22 19:47
Hi

The group names cannot be the same in all these workspaces right. Because
say if we have a group name "Data Eng" in Dev workspace with 5 users, and
in Test with 10 users, in UAT 0 users and Prod 2 users. When we migrate
these workspace groups to account level, there will be only 1 group called
"Data Eng" in the account level and it will have the 10 users in it, and
when this group is federated to the individual workspaces, all Workspace
will have "Data Eng" group with 10 users.
So the ideal way would be to rename the group as we migrate from Workspace
to Account. So this way, when i migrate the groups from my Dev workspace, I
can name it as "Dev_Data_Eng" and this group will now have the correct 5
users in the account level, similarly groups from other env workspaces
(like test, uat and prod) will have corresponding group names in account
level (like Test_Data_Eng with 10 users, Uat_Data_Eng with 0 users and
Prod_data_Eng with 2 users).

@pohlposition <https://github.com/pohlposition> @FastLee
<https://github.com/FastLee> - please share your thoughts.

Thanks
Karthick Baskaran

**Comment by rlsalcido24** [comment] 2023-11-27 01:51
hi @karthickbaskaran-db gotcha that makes sense! One follow up-- in your example where "Data Eng" account group has ten members-- are these ten members basically the same as the ten members in the test workspace? If so how were these ten members added to the "Data Eng" account group-- was the group created with those ten members prior to the logic being run or is there something within the logic that programmatically adds/removes account group members? thanks again!

**Comment by karthickbaskaran-db** [comment] 2023-11-28 15:11
Hi @rlsalcido24 

**_in your example where "Data Eng" account group has ten members-- are these ten members basically the same as the ten members in the test workspace?_** 
Response --> No the group members can be different in Dev, test and other environments. 

 **_If so how were these ten members added to the "Data Eng" account group--_**
Response --> These groups were not sync'd to Account. These groups are at workspace level only.

**Comment by nfx** [comment] 2023-11-30 07:48
It looks like a CLI command to me :)

**Comment by nfx** [comment] 2023-11-30 07:53
Looks like a duplicate of https://github.com/databrickslabs/ucx/issues/342

**Comment by karthickbaskaran-db** [comment] 2023-12-05 14:22
> Should "the workflow not backing up groups" be considered a bug?

Is this one covered as well? or should this be a separate issue?

**Comment by FastLee** [comment] 2023-12-06 16:10
Was resolved with PR #650

**Closed by FastLee** 2023-12-06 16:10 UTC
Labels: step:migrate groups
