### ISSUE TITLE
[BUG]: estimate_table_size_for_migration fails the job when it cannot find a table

### ISSUE THREAD

**Issue by pritishpai** [databrickslabs/ucx#807] opened 2024-01-17 16:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

estimate_table_size_for_migration fails the job when it cannot find a table with the error
RuntimeError: [DELTA_TABLE_NOT_FOUND] Delta table `dais_dlt_meta_<REDACTED>`.`bronze_dataflowspec_cdc` doesn't exist.

### Expected Behavior

Should log the error and fail gracefully

### Steps To Reproduce

Run UCX with default settings on Azure field-eng-east

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
15:56:23 INFO [databricks.labs.ucx] {MainThread} UCX v0.9.0 After job finishes, see debug logs at /Workspace/Users/pritish.pai@databricks.com/.ucx/logs/assessment/run-625517492603035/estimate_table_size_for_migration.log
15:56:23 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx_ppai.table_size] fetching table_size inventory
15:56:23 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [spark][fetch] SELECT * FROM hive_metastore.ucx_ppai.table_size
15:56:24 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx_ppai.table_size] crawling new batch for table_size
15:56:24 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx_ppai.tables] fetching tables inventory
15:56:24 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [spark][fetch] SELECT * FROM hive_metastore.ucx_ppai.tables
15:56:26 DEBUG [databricks.labs.ucx.hive_metastore.table_size] {MainThread} Evaluating hive_metastore.dab_demo_dev.filtered_taxis table size.
15:56:26 DEBUG [databricks.labs.ucx.hive_metastore.table_size] {MainThread} Evaluating hive_metastore.dab_dlt_demo_dev.filtered_taxis table size.
15:56:27 DEBUG [databricks.labs.ucx.hive_metastore.table_size] {MainThread} Evaluating hive_metastore.dais_dlt_meta_<REDACTED>.bronze_dataflowspec_cdc table size.
15:56:27 DEBUG [databricks.labs.ucx.hive_metastore.table_size] {MainThread} Evaluating hive_metastore.dais_dlt_meta_144952dc1d4b4db5ad7fbd53669a0cb4.silver_dataflowspec_cdc table size.
15:56:27 DEBUG [databricks.labs.ucx.hive_metastore.table_size] {MainThread} Evaluating hive_metastore.dais_dlt_meta_<REDACTED>.bronze_dataflowspec_cdc table size.
15:56:28 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/pritish.pai@databricks.com/.ucx/logs/assessment/run-625517492603035/estimate_table_size_for_migration.log` locally to troubleshoot with more details. [DELTA_TABLE_NOT_FOUND] Delta table `dais_dlt_meta_<REDACTED>`.`bronze_dataflowspec_cdc` doesn't exist.
15:56:28 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/table_size.py", line 71, in _safe_get_table_size
    return self._spark._jsparkSession.table(table_full_name).queryExecution().analyzed().stats().sizeInBytes()
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/databricks/spark/python/pyspark/errors/exceptions/captured.py", line 194, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [DELTA_TABLE_NOT_FOUND] Delta table `dais_dlt_meta_<REDACTED>`.`bronze_dataflowspec_cdc` doesn't exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 179, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 68, in estimate_table_size_for_migration
    table_size.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/table_size.py", line 66, in snapshot
    return self._snapshot(partial(self._try_load), partial(self._crawl))
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 283, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/table_size.py", line 45, in _crawl
    size_in_bytes = self._safe_get_table_size(table.key)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/table_size.py", line 76, in _safe_get_table_size
    raise RuntimeError(str(e)) from e
RuntimeError: [DELTA_TABLE_NOT_FOUND] Delta table `dais_dlt_meta_<REDACTED>`.`bronze_dataflowspec_cdc` doesn't exist.
```

**Comment by nfx** [comment] 2024-01-17 16:28
Fixed in https://github.com/databrickslabs/ucx/commit/b249e86cae0683e5c58de658c90d5f0ec923979c
duplicate of https://github.com/databrickslabs/ucx/issues/778

**Closed** 2024-01-17 16:28 UTC
Labels: bug, needs-triage
