### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by gangvijay** [databrickslabs/ucx#1892] opened 2024-06-12 15:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Environment:

Python Version: 3.11.1
Databricks CLI v0.212.4

Error:

C:\Users\nalajv1>databricks labs upgrade ucx -p pcds-dev
Traceback (most recent call last):
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 50, in <module>
    from databricks.labs.ucx.contexts.account_cli import AccountContext
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\contexts\account_cli.py", line 7, in <module>
    from databricks.labs.ucx.account.aggregate import AccountAggregate
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\account\aggregate.py", line 14, in <module>
    from databricks.labs.ucx.contexts.workspace_cli import WorkspaceContext
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\contexts\workspace_cli.py", line 17, in <module>
    from databricks.labs.ucx.contexts.application import CliContext
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\contexts\application.py", line 18, in <module>
    from databricks.labs.ucx.source_code.python_libraries import PythonLibraryResolver
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\source_code\python_libraries.py", line 14, in <module>
    from databricks.labs.ucx.source_code.graph import (
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\source_code\graph.py", line 10, in <module>
    from databricks.labs.ucx.source_code.base import Advisory
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\source_code\base.py", line 9, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'
Error: installer: exit status 1

### Expected Behavior

I should be able to install ucx successfully on workspace

### Cloud

AWS

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
C:\Users\nalajv1>databricks labs upgrade ucx -p pcds-dev
Traceback (most recent call last):
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 50, in <module>
    from databricks.labs.ucx.contexts.account_cli import AccountContext
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\contexts\account_cli.py", line 7, in <module>
    from databricks.labs.ucx.account.aggregate import AccountAggregate
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\account\aggregate.py", line 14, in <module>
    from databricks.labs.ucx.contexts.workspace_cli import WorkspaceContext
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\contexts\workspace_cli.py", line 17, in <module>
    from databricks.labs.ucx.contexts.application import CliContext
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\contexts\application.py", line 18, in <module>
    from databricks.labs.ucx.source_code.python_libraries import PythonLibraryResolver
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\source_code\python_libraries.py", line 14, in <module>
    from databricks.labs.ucx.source_code.graph import (
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\source_code\graph.py", line 10, in <module>
    from databricks.labs.ucx.source_code.base import Advisory
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\source_code\base.py", line 9, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'
Error: installer: exit status 1
```

**Comment by ericvergnaud** [comment] 2024-06-13 10:25
Duplicate of #1875

**Closed by ericvergnaud** 2024-06-13 10:25 UTC
Labels: bug, needs-triage
