### ISSUE TITLE
Create an inventory of Azure Service Principals who has access to storage by scanning all init scripts

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#413] opened 2023-10-08 17:54 UTC
As part of https://github.com/databrickslabs/ucx/pull/326 the following are taken care of -
1. Scanned spark config all clusters, jobs, cluster policies, pipelines for Azure Service Principals who has access to storage and flagged
2. Scanned cluster scoped and global init scripts for Azure Service Principals who has access to storage and flagged

In this issue the following pending item is meant to be taken care of -

Create an inventory of all Azure SPNs who has access to storage **from all the init scripts (cluster and global)** and add it to the "azure_service_principals" table in HMS.

Related to https://github.com/databrickslabs/ucx/issues/249

**Comment by pohlposition** [comment] 2023-10-09 16:55
Relates to https://github.com/databrickslabs/ucx/issues/415

**Comment by nfx** [comment] 2023-10-10 13:32
Duplicate of #415

**Closed by nfx** 2023-10-10 13:32 UTC
Labels: wontfix, step:assessment, step:sync tables, step:upgrade dbsql, step:upgrade clusters
