### ISSUE TITLE
Add Table Migration Progress Chart to a dashboard

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#377] opened 2023-10-04 13:48 UTC
Add support for pie charts and include a widget for table migration progress.
This will then be used for all the other migration elements.

**Comment by larsgeorge-db** [comment] 2023-10-04 20:08
I can add the support for Pie charts, but where do we get the progress value from? What query does retrieve that? @FastLee

**Comment by nfx** [comment] 2023-10-05 13:38
can't it be a % counter?

**Comment by nfx** [comment] 2023-12-06 16:30
duplicate of https://github.com/databrickslabs/ucx/issues/652

**Closed by nfx** 2023-12-06 16:30 UTC
Labels: enhancement, step:assessment
