### ISSUE TITLE
[FEATURE]: Add CTAS table migration function

### ISSUE THREAD

**Issue by qziyuan** [databrickslabs/ucx#1340] opened 2024-04-09 16:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Parent issues:
- https://github.com/databrickslabs/ucx/issues/889
- https://github.com/databrickslabs/ucx/issues/332

When migrate managed dbfs root non-delta tables, and certain external tables, we need to run CTAS.

### Proposed Solution

- Create a function that can create a UC table using CTAS.
- The CTAS should preserve the partition columns if any.
- The function should be able to be used in either managed or external table migration. In case, external table migration, it should be able to create the table in a provided table location. The location will be passed in by the migration function who calls this CTAS function.

**Comment by nfx** [comment] 2024-04-10 12:24
@qziyuan isn't it a duplicate of https://github.com/databrickslabs/ucx/issues/332?..

**Comment by qziyuan** [comment] 2024-04-10 17:05
> @qziyuan isn't it a duplicate of #332?..

@nfx I put the #332 as a parent issue. This issue is meant to create a CTAS function that can be reused by both #332 and #889. Once this issue is completed, what left in #332 is to add a workflow task and calls this CTAS function.

**Closed** 2024-04-18 19:28 UTC
Labels: step:sync tables
