### ISSUE TITLE
workspace_listing task got: KeyError: 'object_type'

### ISSUE THREAD

**Issue by rogerding-db** [databrickslabs/ucx#563] opened 2023-11-07 19:55 UTC
ucx 0.5.0, run in a customer's workspace
https://adb-8498556309875730.10.azuredatabricks.net/?o=8498556309875730
the workspace_listing task got following error:

`KeyError: 'object_type'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.ipykernel/1573/command--1-1331963183:18
     15 entry = [ep for ep in metadata.distribution("databricks_labs_ucx").entry_points if ep.name == "runtime"]
     16 if entry:
     17   # Load and execute the entrypoint, assumes no parameters
---> 18   entry[0].load()()
     19 else:
     20   import databricks_labs_ucx

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:445, in main(*argv)
    443 if len(argv) == 0:
    444     argv = sys.argv
--> 445 trigger(*argv)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py:149, in trigger(*argv)
    146         f.write(f"[run #{workflow_run_id}](/#job/{job_id}/run/{workflow_run_id})\n")
    148 try:
--> 149     current_task.fn(cfg)
    150 except BaseException as error:
    151     log_file_for_cli = str(log_file).lstrip("/Workspace")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:292, in workspace_listing(cfg)
    288 ws = WorkspaceClient(config=cfg.to_databricks_config())
    289 crawler = WorkspaceListing(
    290     ws, RuntimeBackend(), cfg.inventory_database, num_threads=cfg.num_threads, start_path=cfg.workspace_start_path
    291 )
--> 292 crawler.snapshot()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py:260, in WorkspaceListing.snapshot(self)
    259 def snapshot(self) -> list[WorkspaceObjectInfo]:
--> 260     return self._snapshot(self._try_fetch, self._crawl)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py:229, in CrawlerBase._snapshot(self, fetcher, loader)
    227         raise err
    228 logger.debug(f"[{self._full_name}] crawling new batch for {self._table}")
--> 229 loaded_records = list(loader())
    230 self._append_records(loaded_records)
    231 return loaded_records

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py:253, in WorkspaceListing._crawl(self)
    250     continue
    251 raw = obj.as_dict()
    252 yield WorkspaceObjectInfo(
--> 253     object_type=raw["object_type"],
    254     object_id=str(raw["object_id"]),
    255     path=raw["path"],
    256     language=raw.get("language", None),
    257 )

KeyError: 'object_type'`

**Comment by nfx** [comment] 2023-11-07 23:48
Duplicate of #521

**Closed by nfx** 2023-11-07 23:48 UTC
Labels: bug
