### ISSUE TITLE
[BUG]: Re-run assessment after changing local group names

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#1909] opened 2024-06-14 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Reported by a UCX user
1. Run assessment
2. Change a local group names after running the assessment.
3. Re-run the assessment

Some tables appear to reflect the changes but not all:
Have changes:
- grant_detail
- groups

Do NOT have the changes:
- permissions
- grants
After manually changing them and re-running the group-migration - it now appear oke

### Expected Behavior

All tables should reflect the changes (or none)

### Steps To Reproduce

1. Run assessment
2. Change a local group names after running the assessment.
3. Re-run the assessment

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment] 2024-07-05 19:22
Duplicate of #880

**Closed by nfx** 2024-07-05 19:22 UTC
Labels: bug, needs-triage
