### ISSUE TITLE
assess_jobs fails with [CANNOT_BE_NONE] Argument `obj` can not be None because of missing init scripts

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#522] opened 2023-10-30 01:18 UTC
This was run on the ucx-0.5.0 release

I ran the assessment on field-eng-east and the `assess_jobs` task failed with:

```
06:05:18 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/jason@databricks.com/.ucx/logs/assessment/run-960852618228325/assess_jobs.log` locally to troubleshoot with more details. [CANNOT_BE_NONE] Argument `obj` can not be None.
```

STACK TRACE:
```
File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 218, in assess_jobs
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 557, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 230, in _snapshot
    self._append_records(loaded_records)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 235, in _append_records
    self._backend.save_table(self._full_name, items, self._klass, mode="append")
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 135, in save_table
```

I dug through the logs and it looks like there are a few jobs clusters associated with cluster policies where an init script is expected, but cannot be found.  I investigated one such cluster policy through the UI.  there were 7 Jobs associated with the Policy, but none of their configurations had an init script.  Nor did any of the Global init scripts resemble what was in the log.

```
06:05:18 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/policies/clusters/get?policy_id=D9610A22110002E0
< 200 OK
< {
<   "created_at_timestamp": 1632688347000,
<   "definition": "{\"dbus_per_hour\": {\"type\": \"range\", \"maxValue\": 100}, \"num_workers\": {\"type\": \"range\", \"minValue... (644 more bytes)",
<   "is_default": false,
<   "name": "bircp1",
<   "policy_id": "D9610A22110002E0"
< }

06:05:18 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/dbfs/read?path=/user/USERNAME@DOMAIN.COM/oracle_install.sh
< 404 Not Found
< {
<   "error_code": "RESOURCE_DOES_NOT_EXIST",
<   "message": "No file or directory exists on path /user/USERNAME@DOMAIN>COM/oracle_install.sh."
< }

```

I think we should check for missing resources and then log a **WARN** about it, and carry on.  If the resource doesn't exist, there is nothing to assess, and it's not being used anyway.

**Comment by pohlposition** [comment] 2023-10-30 16:49
This may have been fixed in main.  I can retest against main

**Comment by nfx** [comment] 2023-11-07 23:47
Duplicate of #503

**Closed by nfx** 2023-11-07 23:47 UTC
Labels: bug, step:assessment
