### ISSUE TITLE
[FEATURE]: PARTIAL GROUP MIGRATION

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/ucx#2080] opened 2024-07-04 04:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Hi Team,

if I understand the  Group migration 
it migrate local groups by creating temp group and finally delete the local ws group
This will work out if we  do a complete migration 
But if we do a phase wise migration where UC clusters and normal Table ACL hive metastore clusters  should co-exist
What is the way to solve this scenario

Need Advice.

### Proposed Solution

Currently we are planning to create a copy of local ws group and then migrate it so that both groups co-exist post group migration.

**Comment by asnare** [comment] 2024-07-04 09:34
I understand why you're interested in phased migration and I think there's common ground between this feature request and issue #880.

@SomanathSankaran: Would that also help or get you what you want?

**Comment by SomanathSankaran** [comment] 2024-07-04 11:52
@asnare  Basically the problem we have here is say we 10 DB which are attached to dev_group
and we migrate only 3 dbs first then remaining 7 DBs are still accessed though hive legacy Table ACL.
Since we ran group migration all these will be converted to account level group as part of UC Catalog.
Then in that case what will happen for the other tables which are accessed through table acl (legacy ) if the ws groups are getting deleted

**Comment by asnare** [comment] 2024-07-05 07:49
@SomanathSankaran Thanks for clarifying the scenario; I'm going to talk to the team about this.

If you don't mind me restating the concern: it's about the safety of deleting migrated WS groups when the entire WS wasn't within the scope of the migration (and the groups might therefore be required).

**Comment by nfx** [comment] 2024-07-05 19:17
duplicate of #880

**Closed by nfx** 2024-07-05 19:17 UTC
Labels: enhancement, needs-triage
