### ISSUE TITLE
Create Azure Storage account ACL inventory for credential passthrough

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#883] opened 2024-02-05 15:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Perform inventory of azure storage account ACL defined for passthrough clusters and prepare inventory 
Extend the save_azure_storage_accounts cli cmd to include the output of this inventory 

Related:
- https://github.com/databrickslabs/ucx/issues/321

### Proposed Solution

To be discussed

**Comment by nfx** [comment] 2024-04-23 12:06
Duplicate of #321

**Closed by nfx** 2024-04-23 12:06 UTC
Labels: cloud/azure, London-Workshop, migrate/access-control

**Comment by HariGS-DB** [comment] 2024-04-23 21:36
@nfx I think this issue is not duplicate of 321. This issue is a cli cmd which is run by an azure access persona (like the principal-prefix-access) which will scan all credential pass through and prepare another csv file. 
Issue 321 will then use that to apply permission as part of the table migration process. what do you think
