### ISSUE TITLE
[FEATURE]: By mapping SQL Warehourse Instance Profiles permission to UC permission when migrating tables

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#2238] opened 2024-07-24 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When using Glue as an External metastore, it is possible to set permissions at the Table level and also at the storage level.

Currently, instance profile permission of interactive clusters is migrated when doing table migration, but it doesn't cover instance profile used by SQL warehouse. if the warehouse has an instance profile that is different from the interactive cluster profile, then its permission will be missed. 

### Proposed Solution

Include SQL warehouse instance profile and its permission along with interactive cluster permission when migrating tables

**Comment by HariGS-DB** [comment] 2024-07-25 23:57
@william-conti in this case are you referring to table access control cluster or SQL warehouse using glue metastore? or does it apply to standard interactive cluster using a instance profile and connecting to ext metastore?

**Comment by HariGS-DB** [comment] 2024-07-26 09:42
After speaking to @william-conti the issue is broken into two sub-categories.
1. UCX currently support migrating instance profile permission when doing table migration, but it doesn't cover warehouse instance profile. So if warehouse has a instance profile that is different from interactive cluster profile, then its permission will be missed. This will be addressed in this issue
2. You can have a scenario where workspace 1 using a instance profile which only has read permission on the table, but workspace 2 is using different instance profile that has write permission on the same table. When you migrate only one workspace, the migrated UC table will have incomplete permission. This needs to be handled as part of the wider issue #335

**Closed** 2024-07-30 13:21 UTC
Labels: cloud/aws, migrate/access-control, feat/external-hms
