### ISSUE TITLE
[BUG]: Integration tests failure. Integration tests are not designed to run in parallel.

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#876] opened 2024-02-03 11:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Integration tests are failing with high frequency. Some of the tests are not designed to run in parallel with other test runs.

### Expected Behavior

Integration tests should be designed to not interfere with other runs.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment] 2024-02-03 21:49
https://github.com/databrickslabs/sandbox/pull/69 once this is connected to test environments and is deployed properly, we can collect which exact tests are flaky and the reasons behind their flakiness.

**Comment by nfx** [comment] 2024-02-03 21:50
> Steps To Reproduce

No steps to reproduce, closing this issue as not concrete enough

**Closed** 2024-02-03 21:51 UTC
Labels: bug, needs-triage
