### ISSUE TITLE
[FEATURE]: Enhance Feature.yaml

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#821] opened 2024-01-20 17:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Enhance the feature request template and Contributing.md document to provide more detailed guidelines for common code and document feedback items.

### Proposed Solution

- [ ] Code Feedback to improve usability and maintainability
  - [ ] Test coverage warnings have been cleared with sufficient unit test coverage
  - [ ] Exceptions and errors are captured and logged and not 'swallowed'
  - [ ] Expect exceptions from high volume API calls (e.g. `DESCRIBE TABLE`) and handle allowing for continuation of loop.
  - [ ] Retry logic loops only on intermittent overloaded API responses. Guard against python code errors and other exceptions causing Retry loops
  - [ ] Log messages provide needed context information to speed problem determination and resolution.
  - [ ] Secrets and credentials are not logged
  - [ ] Functions have strongly typed signatures and returns including functions that may conditionally return `None`
  - [ ] Avoid inline 'magic' constants and literals
  - [ ] Complex functions provide docstrings descriptions.
  - [ ] Commands validate arguments
  - [ ] Commands argument usage is consistent
  - [ ] Code validates external dependencies
  - [ ] Code validates access permissions 
  - [ ] Code provides a 'soft exit' for automated assessment where dependencies are not met?
  - [ ] Code is friendly to users, anticipating common issues blocking successful use of this feature
  - [ ] Unit Tests include 'unhappy' paths
  - [ ] Feature requires an additional level access that Databricks platform admins may not have. 

- [ ] Sufficient user documentation provided
  - [ ] Prerequisites and dependencies are documented
  - [ ] Additional installation and setup requirements are documented
  - [ ] Additional troubleshooting information is provided
  - [ ] Additional assessment finding documentation is provided
  - [ ] The results are documented
  - [ ] Feature assumptions

### Additional Context

Trying to be clear and raise the bar to better on-board new contributors; also need scale the learnings from past bug reports.

**Comment by nfx** [comment] 2024-01-20 18:36
I don't understand what this is about and what is automatable here

**Comment by pohlposition** [comment] 2024-01-29 17:16
Is this to enhance the PR template so that these things become checkboxes for contributors to validate (before submitting PR)?

**Comment by nfx** [comment] 2024-02-05 18:20
Duplicate of https://github.com/databrickslabs/ucx/issues/895

**Closed by nfx** 2024-02-05 18:20 UTC
Labels: enhancement, needs-triage
