### ISSUE TITLE
[FEATURE]: Migrate`EXTERNAL` tables in `PARQUET`, `CSV`, `JSON`, and `TEXT` using the `ucx.tables.table_format` column as determinant

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1113] opened 2024-03-25 17:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

...

### Proposed Solution

CTAS

**Comment by qziyuan** [comment] 2024-04-09 05:35
duplicate of #889

**Closed by qziyuan** 2024-04-09 05:35 UTC
Labels: step:sync tables
