### ISSUE TITLE
Assessment job failing on wheel not found on a workspace without internet connection

### ISSUE THREAD

**Issue by karthikgk25** [databrickslabs/ucx#538] opened 2023-10-31 22:06 UTC
Any advice on how to resolve this error?

**_run failed with error message
 Python wheel with name databricks_labs_ucx could not be found. Please check the driver logs for more details_**

**Comment by nfx** [comment] 2023-10-31 22:10
How was it installed? Provide full steps to repro

**Comment by karthikgk25** [comment] 2023-10-31 22:17
Installation didn’t have any issues. Installed through Mac Terminal by running install.sh with default configs.  The workspace doesn’t have internet connection , so the initial run of assessment job failed on libraries. Got the databricks-sdk wheel file and installed as init script on the job cluster. The library issue is resolved but hitting this Python wheel not found issue.

**Comment by nfx** [comment] 2023-11-01 08:29
Okay, it's a platform issue then.

If your workspace is without an internet connection, then do "pip wheel ." in the same folder as ucx, it'll create you a bunch of wheels, that you need to install on clusters. This should fix library installation. Keep in mind, though, that the next update will rewrite the job configurations and you'll need this hack again.

Can you please give us more details on how the internet is blocked for workspaces - we may replicate this on our CI environments.

**Comment by karthikgk25** [comment] 2023-11-01 12:49
> Okay, it's a platform issue then.
> 
> If your workspace is without an internet connection, then do "pip wheel ." in the same folder as ucx, it'll create you a bunch of wheels, that you need to install on clusters. This should fix library installation. Keep in mind, though, that the next update will rewrite the job configurations and you'll need this hack again.
> 
> Can you please give us more details on how the internet is blocked for workspaces - we may replicate this on our CI environments.

Thank you. I am going to check with cloud team on workspace restrictions to outside network.
Can you elaborate with more details on pip wheel on ucx folder please?

**Comment by nfx** [comment] 2023-11-01 19:34
Something like 
```
python3 -m pip wheel --wheel-dir ~/Downloads/all-ucx-dependencies
```

**Comment by karthikgk25** [comment] 2023-11-01 20:04
Thanks. I was able to install the dependencies on the clusters. But the assessment job is still failing with "Python wheel with name databricks_labs_ucx could not be found. Please check the driver logs for more details. "

**Comment by nfx** [comment] 2023-11-02 09:08
@karthikgk25 Please contact me at my Databricks email, share the screenshots and the logs. Let's see if we have to do anything special

**Comment by karthikgk25** [comment] 2023-11-02 13:13
Thanks. Can you share your email or send a test email to karthik@datakafe.com

**Comment by karthikgk25** [comment] 2023-11-08 20:17
@nfx Any guidance on this?

**Comment by nfx** [comment] 2023-11-28 10:02
Duplicate of #573

**Closed by nfx** 2023-11-28 10:02 UTC
Labels: enhancement, installer
